### ISSUE TITLE
Unable to run the method - no r3d.h5 available

### ISSUE THREAD

**Issue by kiryteo** [OrangeeJi/3D-ACE#1]
Hello, thanks for the useful work!
I'm interested in using this method for my data and would like to know if there would be some update regarding the r3d.h5 model file or readme update on training the model on custom data?
Thanks!

**Comment by yingji425** [comment]
Hi, the model used in the code is the one that you want to explain, so it should be a trained model that has already been trained on your own dataset.

I didn't provide the models directly because they were trained on my own tasks and datasets. If provided, the dataset should also be provided. I recommend you train your own network with your dataset, and then use my code to explain it.

For the training stage, I just use the simplest 3D ConvNets and save the entire model as an h5 file using Keras.

After you have a trained model, you need to provide the model path and dataset path in the main.py and run it. I think load model part in my code is here:   
(https://github.com/yingji425/STCE/blob/78ea31852ce7e0e2a01ec4aa85c2ffddf995becc/tcavvideo/model.py#L480C1-L485C47)

`    def import_keras_model(self, saved_path):
        """Loads keras model, fetching bottlenecks, inputs and outputs."""
        self.ends = {}
        self.model = tf.keras.models.load_model(saved_path)
        self.get_bottleneck_tensors()
        self.get_inputs_and_outputs_and_ends()`

I hope this solves your problem.
